namespace SunamoEnums.Enums;

/// <summary>
/// Must be in sunamo, not System.Web.UI. HtmlTextWriterAttribute, because its not available in _UAp
/// </summary>
public enum HtmlTextWriterAttribute
{
    Accesskey = 0,
    Align = 1,
    Alt = 2,
    Background = 3,
    Bgcolor = 4,
    Border = 5,
    Bordercolor = 6,
    Cellpadding = 7,
    Cellspacing = 8,
    Checked = 9,
    Class = 10,
    Cols = 11,
    Colspan = 12,
    Disabled = 13,
    For = 14,
    Height = 15,
    Href = 16,
    Id = 17,
    Maxlength = 18,
    Multiple = 19,
    Name = 20,
    Nowrap = 21,
    Onchange = 22,
    Onclick = 23,
    ReadOnly = 24,
    Rows = 25,
    Rowspan = 26,
    Rules = 27,
    Selected = 28,
    Size = 29,
    Src = 30,
    Style = 31,
    Tabindex = 32,
    Target = 33,
    Title = 34,
    Type = 35,
    Valign = 36,
    Value = 37,
    Width = 38,
    Wrap = 39,
    Abbr = 40,
    AutoComplete = 41,
    Axis = 42,
    Content = 43,
    Coords = 44,
    DesignerRegion = 45,
    Dir = 46,
    Headers = 47,
    Longdesc = 48,
    Rel = 49,
    Scope = 50,
    Shape = 51,
    Usemap = 52,
    VCardName = 53
}
